### ISSUE TITLE
Make function more general

### ISSUE THREAD

**Issue by fiferboy** [quisys/bashtar#3]
Make your function more general so it can be used over and over. Something like:

```
play-note("a")
play-note("f-on-high-g")
...
play-note() {
aplay sounds/$1.wav >/dev/null 2>&1 &
}
```

**Comment by quisys** [comment]
I'll look into this. This code example throws syntax errors, but I'm sure it's possible to impliment something similar.

**Comment by quisys** [comment]
Implimented. Thanks for the issue.
